version: '3'

services:
  elasticsearch:
    build: elasticsearch/
    command: elasticsearch -Des.network.host="0.0.0.0"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - ES_HEAP_SIZE=384m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    environment:
      - LS_HEAP_SIZE=256m
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge
